name: rag_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch
  - transformers
  - faiss-cpu
  - pip:
    - fastapi>=0.110.0
    - uvicorn[standard]>=0.27.0
    - langgraph>=0.2.0
    - psycopg2-binary>=2.9.9
    - sqlalchemy>=2.0.25
    - python-dotenv
    - pydantic
    - alembic>=1.13.1
    - structlog>=23.2.0
    - cryptography
    - python-multipart
    - sentence-transformers
    - pypdf
    - pandas
